clean:
	rm -f *.aux
	rm -f */*.aux
	rm -f *.bbl
	rm -f *.blg
	rm -f *.fls
	rm -f *.lof
	rm -f *.log
	rm -f *.lot
	rm -f *.toc
	rm -f *-blx.bib
	rm -f *.out
	rm -f *.run.xml
	rm -f pdfa.xmpi
	rm -f *.fdb_latexmk
	rm -f '${fname}.synctex(busy)'
	rm -f *.synctex.gz
	rm -f ${fname}.pdf